name = "siggen"
description = ""
version = "0.1.0-dev"

authors = ["krispyensign"]
maintainers = ["krispyensign <futralj@gmail.com>"]
maintainers-logins = ["krispyensign"]
licenses = "MIT"
website = ""
tags = []

executables = ["siggen"]

[[depends-on]]
aws = "^24.0.0"
